# <h2 align="center">Student Learning Analysis Python Practice</h2> #

## IMPORT ##

In [6]:
import pandas as pd
import numpy as np

## READ ##

In [8]:
student = pd.read_excel(r"D:\Downloads\شييتات اكسل\online_learning_data_practice.xlsx", sheet_name="Students")
learning_activity = pd.read_excel(r"D:\Downloads\شييتات اكسل\online_learning_data_practice.xlsx", sheet_name="Learning_Activity")

print("done")

done

## ISNA ##

In [148]:
student[student.isna().any(axis=1)].head()

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Weekly_Study_Hours,Year,Month
44,STU1044,Habiba Ahmed,20,Female,Giza,NaT,Master,Standard,19.0,<NA>,<NA>
53,STU1053,Fatma Ibrahim,22,Female,Tanta,NaT,Bachelor,Premium,18.0,<NA>,<NA>
23,STU1023,Hassan Hassan,19,Male,Alexandria,NaT,High School,Premium,18.0,<NA>,<NA>
93,STU1093,Nour Sayed,25,Male,Mansoura,NaT,Bachelor,Premium,17.0,<NA>,<NA>
43,STU1043,Mariam Hassan,27,Female,Mansoura,NaT,Master,Standard,14.0,<NA>,<NA>

## FILLNA ##

In [10]:
student['City']=student['City'].fillna('unknown')

## FILLNA ##

In [11]:
student['Study_Hours_Per_Week']=student['Study_Hours_Per_Week'].fillna(student['Study_Hours_Per_Week'].median())

In [12]:
student

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Study_Hours_Per_Week
0,STU1000,Aya Mohamed,34,Male,cairo,2025-01-01,Master,Standard,14.0
1,STU1001,Nada Khaled,29,Male,Tanta,2025-01-06,Bachelor,Standard,23.0
2,STU1002,Nada Ahmed,24,Female,Mansoura,2025-01-12,Master,Premium,22.0
3,STU1003,Aya Mostafa,19,Male,Aswan,17/01/2025,Bachelor,Standard,7.0
4,STU1004,Fatma Youssef,20,Female,Mansoura,NaN,Master,Basic,2.0
...,...,...,...,...,...,...,...,...,...
97,STU1097,Habiba Mahmoud,18,Male,Giza,2026-06-18,PhD,Basic,10.0
98,STU1098,Mahmoud Sayed,22,Male,Cairo,2026-06-24,PhD,Basic,14.0
99,STU1099,Youssef Ali,33,Male,Tanta,2026-06-30,Bachelor,Basic,4.0
100,STU1005,Nour Khaled,34,Female,Alexandria,2025-01-28,Bachelor,Pro,6.0
101,STU1012,Ahmed Mostafa,22,Female,cairo,2025-03-08,Bachelor,Premium,14.0

## DROP ##

In [13]:
student.drop(4,inplace=True)

In [14]:
student

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Study_Hours_Per_Week
0,STU1000,Aya Mohamed,34,Male,cairo,2025-01-01,Master,Standard,14.0
1,STU1001,Nada Khaled,29,Male,Tanta,2025-01-06,Bachelor,Standard,23.0
2,STU1002,Nada Ahmed,24,Female,Mansoura,2025-01-12,Master,Premium,22.0
3,STU1003,Aya Mostafa,19,Male,Aswan,17/01/2025,Bachelor,Standard,7.0
5,STU1005,Nour Khaled,34,Female,Alexandria,2025-01-28,Bachelor,Pro,6.0
...,...,...,...,...,...,...,...,...,...
97,STU1097,Habiba Mahmoud,18,Male,Giza,2026-06-18,PhD,Basic,10.0
98,STU1098,Mahmoud Sayed,22,Male,Cairo,2026-06-24,PhD,Basic,14.0
99,STU1099,Youssef Ali,33,Male,Tanta,2026-06-30,Bachelor,Basic,4.0
100,STU1005,Nour Khaled,34,Female,Alexandria,2025-01-28,Bachelor,Pro,6.0
101,STU1012,Ahmed Mostafa,22,Female,cairo,2025-03-08,Bachelor,Premium,14.0

## SORT VALUES ##

In [128]:
student.sort_values('Weekly_Study_Hours',ascending=False,inplace=True)

In [129]:
student

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Weekly_Study_Hours,Year,Month
30,STU1030,Ibrahim Ali,23,Female,Cairo,2025-06-15,Bachelor,Pro,24.0,2025,6
92,STU1092,Omar Khaled,30,Male,Aswan,2026-05-22,Bachelor,Standard,24.0,2026,5
49,STU1049,Salma Khaled,19,Male,Mansoura,2025-09-27,Bachelor,Standard,24.0,2025,9
39,STU1039,Ibrahim Khaled,24,Male,Aswan,2025-08-03,High School,Pro,24.0,2025,8
96,STU1096,Ali Khaled,32,Male,cairo,2026-06-13,High School,Basic,24.0,2026,6
...,...,...,...,...,...,...,...,...,...,...,...
9,STU1009,Mariam Hassan,34,Female,Cairo,2025-02-19,Bachelor,Standard,3.0,2025,2
32,STU1032,Mahmoud Mohamed,20,Male,Mansoura,2025-06-26,Bachelor,Standard,3.0,2025,6
82,STU1082,Ali Sayed,25,Male,Alexandria,2026-03-28,Bachelor,Standard,3.0,2026,3
86,STU1086,Aya Sayed,18,Female,Cairo,2026-04-19,Bachelor,Basic,2.0,2026,4
21,STU1021,Aya Hassan,23,Female,Alexandria,2025-04-26,High School,Pro,2.0,2025,4

## MAX ##

In [98]:
student['Age'].max()

np.int64(34)

## DROP_DUPLICATES ##

In [99]:
student.drop_duplicates()

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Weekly_Study_Hours,Year,Month
30,STU1030,Ibrahim Ali,23,Female,Cairo,2025-06-15,Bachelor,Pro,24.0,2025,6
39,STU1039,Ibrahim Khaled,24,Male,Aswan,2025-08-03,High School,Pro,24.0,2025,8
96,STU1096,Ali Khaled,32,Male,cairo,2026-06-13,High School,Basic,24.0,2026,6
92,STU1092,Omar Khaled,30,Male,Aswan,2026-05-22,Bachelor,Standard,24.0,2026,5
49,STU1049,Salma Khaled,19,Male,Mansoura,2025-09-27,Bachelor,Standard,24.0,2025,9
...,...,...,...,...,...,...,...,...,...,...,...
9,STU1009,Mariam Hassan,34,Female,Cairo,2025-02-19,Bachelor,Standard,3.0,2025,2
32,STU1032,Mahmoud Mohamed,20,Male,Mansoura,2025-06-26,Bachelor,Standard,3.0,2025,6
82,STU1082,Ali Sayed,25,Male,Alexandria,2026-03-28,Bachelor,Standard,3.0,2026,3
86,STU1086,Aya Sayed,18,Female,Cairo,2026-04-19,Bachelor,Basic,2.0,2026,4
21,STU1021,Aya Hassan,23,Female,Alexandria,2025-04-26,High School,Pro,2.0,2025,4

## VALUE_COUNTS ##

In [100]:
student["Gender"].value_counts()

Gender
Male      53
Female    48
Name: count, dtype: int64

## NUNIQUE ##

In [101]:
student["Gender"].nunique()

2

## UNIQUE ##

In [102]:
student["Gender"].unique()

<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

## SHAPE ##

In [21]:
student.shape

(101, 9)

## COLUMNS ##

In [22]:
student.columns

Index(['Student_ID', 'Student_Name', 'Age', 'Gender', 'City',
       'Registration_Date', 'Education_Level', 'Learning_Plan',
       'Study_Hours_Per_Week'],
      dtype='str')

## DTYPES ##

In [103]:
student.dtypes

Student_ID                       str
Student_Name                     str
Age                            int64
Gender                           str
City                             str
Registration_Date     datetime64[us]
Education_Level                  str
Learning_Plan                    str
Weekly_Study_Hours           float64
Year                           Int64
Month                          Int64
dtype: object

## SIZE ##

In [24]:
student.size

909

## ILOG ##

In [25]:
student.iloc[5]

Student_ID                  STU1001
Student_Name            Nada Khaled
Age                              29
Gender                         Male
City                          Tanta
Registration_Date        2025-01-06
Education_Level            Bachelor
Learning_Plan              Standard
Study_Hours_Per_Week           23.0
Name: 1, dtype: object

## LOG ##

In [26]:
student.loc[(student["Learning_Plan"]=='Pro') & (student["Gender"]=='Male')]

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Study_Hours_Per_Week
39,STU1039,Ibrahim Khaled,24,Male,Aswan,2025-08-03,High School,Pro,24.0
76,STU1076,Ibrahim Ahmed,21,Male,Mansoura,2026-02-23,Bachelor,Pro,20.0
74,STU1074,Ahmed Mohamed,33,Male,Giza,2026-02-12,PhD,Pro,18.0
7,STU1007,Mahmoud Khaled,34,Male,Aswan,2025-02-08,Master,Pro,13.0
17,STU1017,Youssef Sayed,23,Male,Mansoura,2025-04-04,Bachelor,Pro,12.0
80,STU1080,Nour Ibrahim,31,Male,Cairo,2026-03-17,Bachelor,Pro,7.0

## DESCRIBE ##

In [27]:
student['City'].describe()

count            101
unique            10
top       Alexandria
freq              19
Name: City, dtype: object

## GROUPBY ##

In [41]:
city_analysis=student.groupby('City').agg(
    student_count=('Student_ID','count'),
    avg_study_hours=('Study_Hours_Per_Week','mean')).round({'avg_study_hours':2})

In [44]:
city_analysis

            student_count  avg_study_hours
City
Alexandria             19            11.63
Aswan                  16            14.12
Cairo                  12             9.83
Cairo                   5            14.80
Giza                   13            13.77
Giza                    2            12.50
Mansoura               15            16.67
Tanta                   7            14.86
cairo                  10            12.20
unknown                 2            13.50

In [142]:
plan_avg=student.groupby("Learning_Plan")["Weekly_Study_Hours"].mean().round(2)

In [143]:
plan_avg

Learning_Plan
Basic       12.74
Premium     15.00
Pro         13.00
Standard    13.00
Name: Weekly_Study_Hours, dtype: float64

In [133]:
plan_avg.max()

np.float64(15.0)

In [56]:
plan_avg.min()

np.float64(12.74)

## DATETIME , YEAR , MONTHS ##

In [60]:
student["Registration_Date"] = pd.to_datetime(student["Registration_Date"], errors='coerce')

In [66]:
student["Month"] = student["Registration_Date"].dt.month.astype("Int64")
student["Year"] = student["Registration_Date"].dt.year.astype("Int64")

## RENAME COLUMN ##

In [67]:
student.rename(
    columns={"Study_Hours_Per_Week": "Weekly_Study_Hours"},
    inplace=True
)

In [68]:
student

,Student_ID,Student_Name,Age,Gender,City,Registration_Date,Education_Level,Learning_Plan,Weekly_Study_Hours,Year,Month
30,STU1030,Ibrahim Ali,23,Female,Cairo,2025-06-15,Bachelor,Pro,24.0,2025,6
39,STU1039,Ibrahim Khaled,24,Male,Aswan,2025-08-03,High School,Pro,24.0,2025,8
96,STU1096,Ali Khaled,32,Male,cairo,2026-06-13,High School,Basic,24.0,2026,6
92,STU1092,Omar Khaled,30,Male,Aswan,2026-05-22,Bachelor,Standard,24.0,2026,5
49,STU1049,Salma Khaled,19,Male,Mansoura,2025-09-27,Bachelor,Standard,24.0,2025,9
...,...,...,...,...,...,...,...,...,...,...,...
9,STU1009,Mariam Hassan,34,Female,Cairo,2025-02-19,Bachelor,Standard,3.0,2025,2
32,STU1032,Mahmoud Mohamed,20,Male,Mansoura,2025-06-26,Bachelor,Standard,3.0,2025,6
82,STU1082,Ali Sayed,25,Male,Alexandria,2026-03-28,Bachelor,Standard,3.0,2026,3
86,STU1086,Aya Sayed,18,Female,Cairo,2026-04-19,Bachelor,Basic,2.0,2026,4
21,STU1021,Aya Hassan,23,Female,Alexandria,2025-04-26,High School,Pro,2.0,2025,4

In [146]:
  learning_activity[  learning_activity.isna().any(axis=1)].head()

,Activity_ID,Student_ID,Course,Category,Activity_Date,Lessons_Completed,Quiz_Score,Assignment_Score,Study_Time_Minutes,Completion_Percentage,Platform_Rating
3,ACT5003,STU1023,Machine Learning Basics,AI & ML,NaT,1.0,49.0,98.0,240.0,85.0,3.0
7,ACT5007,STU1083,Excel Advanced Analytics,Spreadsheets,NaT,7.0,56.0,94.0,59.0,11.0,5.0
22,ACT5022,STU1050,Data Visualization with Power BI,Business Intelligence,NaT,8.0,70.0,84.0,190.0,12.0,4.0
33,ACT5033,STU1011,Statistics & Probability,Mathematics,NaT,8.0,45.0,51.0,166.0,50.0,5.0
37,ACT5037,STU1013,SQL Database Fundamentals,Databases,NaT,10.0,64.0,80.0,79.0,64.0,5.0

## FILLNA ##

In [76]:
learning_activity["Lessons_Completed"] = learning_activity["Lessons_Completed"].fillna(learning_activity["Lessons_Completed"].median())

learning_activity["Quiz_Score"] = learning_activity["Quiz_Score"].fillna(
    learning_activity["Quiz_Score"].median()
)

learning_activity["Assignment_Score"] = learning_activity["Assignment_Score"].fillna(
    learning_activity["Assignment_Score"].median()
)

learning_activity["Study_Time_Minutes"] = learning_activity["Study_Time_Minutes"].fillna(
    learning_activity["Study_Time_Minutes"].median()
)

learning_activity["Completion_Percentage"] = learning_activity["Completion_Percentage"].fillna(
    learning_activity["Completion_Percentage"].median()
)

learning_activity["Platform_Rating"] = learning_activity["Platform_Rating"].fillna(
    learning_activity["Platform_Rating"].median()
)

In [147]:
  learning_activity[  learning_activity.isna().any(axis=1)].head()

,Activity_ID,Student_ID,Course,Category,Activity_Date,Lessons_Completed,Quiz_Score,Assignment_Score,Study_Time_Minutes,Completion_Percentage,Platform_Rating
3,ACT5003,STU1023,Machine Learning Basics,AI & ML,NaT,1.0,49.0,98.0,240.0,85.0,3.0
7,ACT5007,STU1083,Excel Advanced Analytics,Spreadsheets,NaT,7.0,56.0,94.0,59.0,11.0,5.0
22,ACT5022,STU1050,Data Visualization with Power BI,Business Intelligence,NaT,8.0,70.0,84.0,190.0,12.0,4.0
33,ACT5033,STU1011,Statistics & Probability,Mathematics,NaT,8.0,45.0,51.0,166.0,50.0,5.0
37,ACT5037,STU1013,SQL Database Fundamentals,Databases,NaT,10.0,64.0,80.0,79.0,64.0,5.0

In [120]:
learning_activity["Activity_Date"] = pd.to_datetime(learning_activity["Activity_Date"], errors='coerce')

In [79]:
learning_activity

,Activity_ID,Student_ID,Course,Category,Activity_Date,Lessons_Completed,Quiz_Score,Assignment_Score,Study_Time_Minutes,Completion_Percentage,Platform_Rating
0,ACT5000,STU1030,Data Visualization with Power BI,Business Intelligence,2025-02-01,8.0,67.0,73.0,163.0,53.0,4.0
1,ACT5001,STU1039,Excel Advanced Analytics,Spreadsheets,2025-02-02,13.0,65.0,61.0,217.0,49.0,5.0
2,ACT5002,STU1035,SQL Database Fundamentals,Databases,2025-02-03,4.0,82.0,96.0,89.0,93.0,1.0
3,ACT5003,STU1023,Machine Learning Basics,AI & ML,NaT,1.0,49.0,98.0,240.0,85.0,3.0
4,ACT5004,STU1094,SQL Database Fundamentals,Databases,2025-02-06,3.0,69.0,91.0,181.0,24.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
417,ACT5417,STU1097,SQL Database Fundamentals,Databases,2026-08-29,2.0,99.0,83.0,156.0,38.0,3.0
418,ACT5418,STU1086,SQL Database Fundamentals,Databases,2026-08-30,8.0,76.0,79.0,163.0,42.0,4.0
419,ACT5419,STU1036,Excel Advanced Analytics,Spreadsheets,2026-09-01,7.0,91.0,67.0,176.0,69.0,3.0
420,ACT5010,STU1003,Machine Learning Basics,AI & ML,2025-02-14,13.0,86.0,73.0,48.0,83.0,3.0
421,ACT5045,STU1032,Data Visualization with Power BI,Business Intelligence,2025-04-03,8.0,50.0,90.0,274.0,32.0,3.0

## MERGE ##

In [89]:
merged_data = pd.merge(student, learning_activity, on="Student_ID")

result = merged_data.groupby(
    ["Student_ID", "Student_Name", "City", "Learning_Plan"]
)["Study_Time_Minutes"].sum().reset_index()
result["Study_Time_Minutes"] = result["Study_Time_Minutes"].astype("Int64")

In [90]:
result

   Student_ID    Student_Name        City Learning_Plan  Study_Time_Minutes
0     STU1000     Aya Mohamed       cairo      Standard                1291
1     STU1001     Nada Khaled       Tanta      Standard                 985
2     STU1002      Nada Ahmed    Mansoura       Premium                 125
3     STU1003     Aya Mostafa       Aswan      Standard                 515
4     STU1005     Nour Khaled  Alexandria           Pro                1666
..        ...             ...         ...           ...                 ...
93    STU1095   Ahmed Ibrahim       Aswan      Standard                 830
94    STU1096      Ali Khaled       cairo         Basic                1261
95    STU1097  Habiba Mahmoud        Giza         Basic                 452
96    STU1098   Mahmoud Sayed       Cairo         Basic                 332
97    STU1099     Youssef Ali       Tanta         Basic                 582

[98 rows x 5 columns]

## Total Study Time by Course for Tanta Students ##

In [92]:
result = pd.merge(
    student[["Student_ID", "City"]],
    learning_activity[["Student_ID", "Course", "Study_Time_Minutes"]],
    on="Student_ID",
    how="left"
)

result[result["City"] == "Tanta"].groupby("Course")["Study_Time_Minutes"].sum().reset_index()

                             Course  Study_Time_Minutes
0  Data Visualization with Power BI               601.0
1          Excel Advanced Analytics               407.0
2           Machine Learning Basics              1584.0
3              Python for Beginners               932.0
4         SQL Database Fundamentals              1561.0
5          Statistics & Probability               637.0

## Average Quiz Score by Course for Bachelor Students ##

In [93]:
result = pd.merge(
    student[["Student_ID", "Education_Level"]],
    learning_activity[["Student_ID", "Course", "Quiz_Score"]],
    on="Student_ID",
    how="left"
)

result[result["Education_Level"] == "Bachelor"].groupby("Course")["Quiz_Score"].mean().reset_index()

                             Course  Quiz_Score
0  Data Visualization with Power BI   65.440000
1          Excel Advanced Analytics   68.615385
2           Machine Learning Basics   66.622222
3              Python for Beginners   69.410256
4         SQL Database Fundamentals   66.574074
5          Statistics & Probability   67.342857

## Total Study Time by Learning Plan ##

In [94]:
result = pd.merge(
    student[["Student_ID", "Learning_Plan"]],
    learning_activity[["Student_ID", "Study_Time_Minutes"]],
    on="Student_ID",
    how="left"
)

result.groupby("Learning_Plan")["Study_Time_Minutes"].sum().reset_index()

  Learning_Plan  Study_Time_Minutes
0         Basic             16240.0
1       Premium             16749.0
2           Pro              9822.0
3      Standard             26999.0

## Average Completion Percentage by City ##

In [95]:
result = pd.merge(
    student[["Student_ID", "City"]],
    learning_activity[["Student_ID", "Completion_Percentage"]],
    on="Student_ID",
    how="left"
)

result.groupby("City")["Completion_Percentage"].mean().reset_index()

         City  Completion_Percentage
0  Alexandria              53.949367
1       Aswan              54.516129
2       Cairo              51.175439
3      Cairo               56.615385
4        Giza              54.254902
5      Giza                57.888889
6    Mansoura              52.288462
7       Tanta              55.382353
8       cairo              55.448980
9     unknown              46.888889

## Highest Quiz Score by Learning Plan ##

In [96]:
result = pd.merge(
    student[["Student_ID", "Learning_Plan"]],
    learning_activity[["Student_ID", "Quiz_Score"]],
    on="Student_ID",
    how="left"
)

result.groupby("Learning_Plan")["Quiz_Score"].max().reset_index()

  Learning_Plan  Quiz_Score
0         Basic        99.0
1       Premium        98.0
2           Pro        99.0
3      Standard        99.0

## Top 5 Students By Total Study Time ##

In [114]:
top_students = (
    pd.merge(
        student[["Student_ID", "Student_Name"]],
        learning_activity[["Student_ID", "Study_Time_Minutes"]],
        on="Student_ID",
        how="inner"
    )
    .groupby(["Student_ID", "Student_Name"])["Study_Time_Minutes"]
    .sum().reset_index()
    .sort_values(by="Study_Time_Minutes",ascending=False)
    .head(5)
)

print(top_students)

   Student_ID     Student_Name  Study_Time_Minutes
27    STU1028    Hassan Khaled              1876.0
4     STU1005      Nour Khaled              1666.0
11    STU1012    Ahmed Mostafa              1382.0
49    STU1050     Ahmed Khaled              1369.0
31    STU1032  Mahmoud Mohamed              1306.0

## students_without_activity ##

In [138]:
result = pd.merge(
    student[["Student_ID", "Student_Name"]],
    learning_activity[["Student_ID", "Course"]],
    on="Student_ID",
    how="left",
)

print(result[result["Course"].isnull()])

    Student_ID  Student_Name Course
334    STU1079  Nada Youssef    NaN

In [125]:
with pd.ExcelWriter("Student_Learning_Analysis.xlsx") as writer:
    student.to_excel(writer, sheet_name="Student", index=False)
    learning_activity.to_excel(writer, sheet_name="Learning_Activity", index=False)